/* Edition-aware public catalogue adapters. No account or API key is needed for
 * Open Library / Apple Books. Google Books is opt-in; Goodreads is an optional
 * publisher-maintained same-origin feed, never an unlabelled scraped rating. */
(function(root,factory){
  if(typeof module==='object'&&module.exports) module.exports=factory(null);
  else root.CatalogueClient=factory(root);
})(typeof window!=='undefined'?window:this,function(root){
  'use strict';
  function create(options){
    var o=options||{}, Core=o.core||(root&&root.BookCore), data=o.data||(root&&root.CatalogueData)||{}, config=o.config||(root&&root.MZR_CONFIG)||{};
    var fetcher=o.fetch||(root&&root.fetch&&root.fetch.bind(root)), storage=o.storage;
    if(storage===undefined)try{storage=root&&root.localStorage;}catch(e){}
    var seeds=Array.isArray(data)?data:(data.books||[]), cache=new Map(), inflight=new Map(), queue=[], active=0, nextStart=0, queueTimer=null;
    var gap=o.requestGap==null?1100:o.requestGap, timeout=o.timeout||8500, HOUR=3600000;
    var langCodes={cs:'cze',en:'eng',sk:'slo',de:'ger',fr:'fre',es:'spa',it:'ita',pl:'pol'};
    var langMap={cs:'cs',cze:'cs',ces:'cs',en:'en',eng:'en',sk:'sk',slo:'sk',slk:'sk',de:'de',ger:'de',deu:'de',fr:'fr',fre:'fr',fra:'fr',es:'es',spa:'es',it:'it',ita:'it',pl:'pl',pol:'pl'};
    function language(value){var list=Array.isArray(value)?value:[value];list=list.map(function(v){var code=String(v&&v.key||v||'').replace('/languages/','').toLowerCase();return langMap[code]||code;}).filter(Boolean);list=Array.from(new Set(list));return list.length===1?(langMap[list[0]]||''):'';}
    function text(v){return String(v&&typeof v==='object'?v.value||'':v||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').trim().slice(0,20000);}
    function date(v){var m=String(Array.isArray(v)?v[0]:v||'').match(/(?:^|\D)(1[0-9]{3}|20[0-9]{2})(?:\D|$)/);return m?Core.year(+m[1]):null;}
    function isbn(v){var a=Array.isArray(v)?v:[v];return a.map(function(x){return String(x||'').replace(/[-\s]/g,'');}).filter(function(x){return /^(?:\d{13}|\d{9}[\dXx])$/.test(x);}).sort(function(a,b){return b.length-a.length;})[0]||'';}
    function clean(book){var b=Core.snapshot(book);b.tags=Core.normalizeTags?Core.normalizeTags(b):b.tags;return b;}
    function linked(books){return Core.linkCatalogue?Core.linkCatalogue(books,seeds):books;}
    function merge(books){return Core.merge([books]);}
    function workMatch(a,b){return !!(a&&b&&((a.olWorkId&&a.olWorkId===b.olWorkId)||(Core.sameWork||Core.sameBook)(a,b)));}
    function flat(books){var out=[];(books||[]).forEach(function(b){out.push(b);(b.editions||[]).forEach(function(e){out.push(e);});});return out;}
    function getCache(key){var entry=cache.get(key);if(!entry&&storage)try{entry=JSON.parse(storage.getItem('za_catalogue_v1:'+key));}catch(e){}if(entry&&entry.until>Date.now())return entry;return null;}
    function setCache(key,value,ttl,error){var entry={until:Date.now()+ttl,value:value,error:error||''};cache.set(key,entry);if(cache.size>60)cache.delete(cache.keys().next().value);if(storage&&!error)try{var keys=Object.keys(storage).filter(function(k){return k.indexOf('za_catalogue_v1:')===0;});if(keys.length>=30)storage.removeItem(keys[0]);storage.setItem('za_catalogue_v1:'+key,JSON.stringify(entry));}catch(e){}return entry;}
    function drain(){if(queueTimer||!queue.length||active>=2)return;var wait=Math.max(0,nextStart-Date.now());if(wait){queueTimer=setTimeout(function(){queueTimer=null;drain();},wait);return;}var task=queue.shift();active++;nextStart=Date.now()+gap;Promise.resolve().then(task.run).then(task.resolve,task.reject).finally(function(){active--;drain();});drain();}
    function schedule(run){return new Promise(function(resolve,reject){var task={run:run,resolve:resolve,reject:reject},expiry=setTimeout(function(){var index=queue.indexOf(task);if(index>=0){queue.splice(index,1);reject(new Error('Katalog čeká na dokončení předchozího hledání'));}},timeout);task.run=function(){clearTimeout(expiry);return run();};queue.push(task);drain();});}
    function request(url,source,ttl){
      var saved=getCache(url);if(saved)return saved.error?Promise.reject(new Error(saved.error)):Promise.resolve(saved.value);
      if(inflight.has(url))return inflight.get(url);
      function run(){var controller=typeof AbortController!=='undefined'?new AbortController():null,timer;
        return Promise.race([Promise.resolve().then(function(){if(!fetcher)throw new Error('Připojení není dostupné');return fetcher(url,controller?{signal:controller.signal}:{});}).then(function(r){if(!r.ok)throw new Error(r.status===429?'Katalog je dočasně vytížený':'HTTP '+r.status);return r.json();}),new Promise(function(_,reject){timer=setTimeout(function(){if(controller)controller.abort();reject(new Error('Katalog neodpověděl včas'));},timeout);})]).then(function(j){if(!j||typeof j!=='object'||j.error||(/openlibrary\.org\/search\.json/.test(url)&&!Array.isArray(j.docs))||(/itunes\.apple\.com\/search/.test(url)&&!Array.isArray(j.results))||(/googleapis\.com\/books\/v1\/volumes/.test(url)&&!Array.isArray(j.items)&&j.totalItems!==0)||(/\/editions\.json/.test(url)&&!Array.isArray(j.entries)))throw new Error('Katalog vrátil neplatná data');setCache(url,j,ttl||6*HOUR);return j;}).catch(function(e){var msg=e.name==='AbortError'?'Katalog neodpověděl včas':e.message||'Připojení není dostupné';setCache(url,null,30000,msg);throw new Error(msg);}).finally(function(){clearTimeout(timer);});}
      var promise=(source==='Open Library'?schedule(run):run()).finally(function(){inflight.delete(url);});inflight.set(url,promise);return promise;
    }
    function mapApple(r){
      var cover=String(r.artworkUrl100||r.artworkUrl60||'').replace(/\/[0-9]{2,4}x[0-9]{2,4}bb\.(jpg|jpeg|png)/i,'/600x600bb.$1');
      return clean({id:'a:'+r.trackId,editionId:'a:'+r.trackId,source:'Apple Books',title:r.trackName,author:r.artistName,year:date(r.releaseDate),yearKind:'edition',language:language(r.languageCodesISO2A||r.languageCodes||r.language),pages:0,tags:r.genres||[],desc:text(r.description),coverUrl:cover,coverUrlL:cover,link:r.trackViewUrl,aRating:r.averageUserRating,aCount:r.userRatingCount||0});
    }
    function apple(q,filters){var countries=filters.language==='en'?['US']:filters.language==='cs'?['CZ']:['CZ','US'];return Promise.allSettled(countries.map(function(country){return request('https://itunes.apple.com/search?term='+encodeURIComponent(q)+'&entity=ebook&country='+country+'&limit=60','Apple Books').then(function(j){if(!Array.isArray(j.results))throw new Error('Katalog vrátil neplatné výsledky');return j.results.filter(function(r){return r.trackId&&r.trackName;}).map(mapApple);});})).then(function(results){var success=results.filter(function(r){return r.status==='fulfilled';});if(!success.length)throw results[0].reason;return success.flatMap(function(r){return r.value;});});}
    var fields='key,title,author_name,first_publish_year,cover_i,subject,ratings_average,ratings_count,editions,editions.key,editions.title,editions.language,editions.isbn,editions.publish_date,editions.publish_year,editions.number_of_pages,editions.cover_i';
    function mapOL(d){
      var base={id:d.key,workId:d.key,olWorkId:d.key,title:d.title,author:(d.author_name||[]).join(', ')||'Neznámý autor',firstPublishYear:date(d.first_publish_year),year:null,yearKind:'original',source:'Open Library',language:'',pages:0,tags:d.subject||[],olRating:d.ratings_average,olCount:d.ratings_count||0,coverUrl:d.cover_i?'https://covers.openlibrary.org/b/id/'+d.cover_i+'-M.jpg':'',coverUrlL:d.cover_i?'https://covers.openlibrary.org/b/id/'+d.cover_i+'-L.jpg':'',link:'https://openlibrary.org'+d.key};
      var editions=d.editions&&Array.isArray(d.editions.docs)?d.editions.docs:[];
      if(!editions.length)return [clean(base)];
      return editions.filter(function(e){return e.key&&e.title;}).map(function(e){var key=e.key.indexOf('/')===0?e.key:'/books/'+e.key,cover=e.cover_i||d.cover_i;return clean(Object.assign({},base,{id:key,editionId:key,olEditionId:key,title:e.title,aliases:e.title===d.title?[]:[d.title],year:date(e.publish_date)||date(e.publish_year),yearKind:'edition',language:language(e.language),isbn:isbn(e.isbn),pages:Core.integer(e.number_of_pages),pageSource:e.number_of_pages?'Open Library · konkrétní vydání':'',coverUrl:cover?'https://covers.openlibrary.org/b/id/'+cover+'-M.jpg':'',coverUrlL:cover?'https://covers.openlibrary.org/b/id/'+cover+'-L.jpg':'',link:'https://openlibrary.org'+key}));});
    }
    function quote(q){return '"'+String(q).replace(/["\\]/g,' ').trim()+'"';}
    function olSearch(query,filters,sort,maxPages){var f=filters||{},q=query;if(f.language&&langCodes[f.language])q+=' AND language:'+langCodes[f.language];if(Core.year(f.year))q+=' AND publish_year:'+Core.year(f.year);var url='https://openlibrary.org/search.json?q='+encodeURIComponent(q)+'&limit=60&fields='+encodeURIComponent(fields)+'&lang='+encodeURIComponent(f.language&&f.language!=='all'?f.language:'cs');if(sort)url+='&sort='+encodeURIComponent(sort);
      function page(offset,left){return request(url+'&offset='+offset,'Open Library').then(function(j){var books=j.docs.filter(function(d){return /^\/works\/OL\d+W$/.test(d.key)&&d.title;}).flatMap(mapOL),total=Number(j.numFound==null?j.num_found:j.numFound);if(left>1&&j.docs.length===60&&total>offset+j.docs.length)return page(offset+60,left-1).then(function(next){return books.concat(next);}).catch(function(){return books;});return books;});}
      return page(0,Math.max(1,Math.min(2,maxPages||1)));
    }
    // Browse both relevance and recent works. A single newest page can exclude
    // popular translations; an age cutoff also excludes their new editions.
    function olBrowse(query,filters){return Promise.allSettled([olSearch(query,filters,null,2),olSearch(query,filters,'new')]).then(function(results){var success=results.filter(function(r){return r.status==='fulfilled';});if(!success.length)throw results[0].reason;return success.flatMap(function(r){return r.value;});});}
    function mapGoogle(item){var v=item.volumeInfo||{},cover=v.imageLinks&&(v.imageLinks.thumbnail||v.imageLinks.smallThumbnail)||'';cover=cover.replace(/^http:/,'https:').replace('&edge=curl','');return clean({id:'g:'+item.id,editionId:'g:'+item.id,source:'Google Books',title:v.title,author:(v.authors||[]).join(', '),year:date(v.publishedDate),yearKind:'edition',language:language(v.language),isbn:isbn((v.industryIdentifiers||[]).map(function(i){return i.identifier;})),pages:Core.integer(v.pageCount),pageSource:v.pageCount?'Google Books · konkrétní vydání':'',tags:v.categories||[],desc:text(v.description),coverUrl:cover,coverUrlL:cover,link:v.infoLink,gRating:v.averageRating,gCount:v.ratingsCount||0});}
    function google(query,filters){var url='https://www.googleapis.com/books/v1/volumes?q='+encodeURIComponent(query)+'&printType=books&maxResults=40&key='+encodeURIComponent(config.googleBooksApiKey);if(filters.language&&filters.language!=='all')url+='&langRestrict='+encodeURIComponent(filters.language);if(filters.sort==='newest')url+='&orderBy=newest';return request(url,'Google Books').then(function(j){if(!Array.isArray(j.items)&&j.totalItems!==0)throw new Error('Katalog vrátil neplatné výsledky');return (j.items||[]).filter(function(i){return i.id&&i.volumeInfo&&i.volumeInfo.title;}).map(mapGoogle);});}
    function available(book,filters){var f=filters||{};return (!f.language||f.language==='all'||book.language===f.language)&&(!Core.year(f.year)||book.year===Core.year(f.year));}
    function bundles(book){return /\bbox(?:ed)?\s*set\b|\bboxset\b|\bbundle\b|\bcomplete collection\b|\bomnibus\b|\bcollection of\b|\bkomplet\b|\bbox knih\b/i.test(book.title);}
    function aggregate(jobs,local,filters,predicate){return Promise.allSettled(jobs.map(function(j){return j.run();})).then(function(results){var issues=[],books=local.slice(),success=[];results.forEach(function(r,i){if(r.status==='fulfilled'){books=books.concat(r.value);success.push(jobs[i].source);}else issues.push({source:jobs[i].source,message:r.reason.message||'Připojení není dostupné'});});books=merge(linked(books));if(predicate)books=books.filter(predicate);return enrichBatch(books,18).then(function(enriched){return Promise.all(enriched.map(ratings));}).then(function(enriched){return {books:enriched.filter(function(b){return available(b,filters);}),failed:issues.length,total:jobs.length,issues:issues,sources:success};});});}
    function matchingSeeds(q){return seeds.filter(function(b){return Core.relevance(b,q)>0;});}
    function search(q,filters){q=String(q||'').trim().slice(0,300);var f=filters||{};if(!q)return Promise.resolve({books:[],failed:0,total:0,issues:[],sources:[]});var local=matchingSeeds(q), number=isbn(q), authored=local.filter(function(b){return Core.norm(b.author).replace(/\s/g,'')===Core.norm(q).replace(/\s/g,'')||(b.authorAliases||[]).some(function(a){return Core.norm(a)===Core.norm(q);});});var query;
      if(number&&number===q.replace(/[-\s]/g,''))query='isbn:'+number;
      else if(authored.length)query='author:'+quote(authored[0].author);
      else{var exact=local.filter(function(b){return [b.title].concat(b.aliases||[]).some(function(t){return Core.norm(t)===Core.norm(q);});});var titles=Array.from(new Set(exact.flatMap(function(b){return [b.title].concat(b.aliases||[]);}))).slice(0,5);query=titles.length?'('+titles.map(function(t){return 'title:'+quote(t);}).join(' OR ')+')':'('+quote(q)+' OR title:'+quote(q)+' OR author:'+quote(q)+')';}
      var jobs=[{source:'Open Library',run:function(){return olSearch(query,f);}},{source:'Apple Books',run:function(){return apple(q,f);}}];if(config.googleBooksApiKey)jobs.push({source:'Google Books',run:function(){return google(number?'isbn:'+number:q,f);}});
      return aggregate(jobs,local,f,function(b){return Core.relevance(b,q)>0;});
    }
    var subjects={romantika:['romance'],romance:['romance'],romantasy:['fantasy','romance'],fantasy:['fantasy'],drak:['dragons'],draci:['dragons'],dragons:['dragons'],kingdoms:['kingdoms','princesses','princes','royalty','kings and rulers'],království:['kingdoms','princesses','princes','royalty','kings and rulers'],magie:['magic'],magic:['magic'],hokej:['hockey','ice hockey'],hockey:['hockey'],fairies:['fairies'],víly:['fairies'],adventure:['adventure'],dobrodružství:['adventure'],detektivka:['mystery','detective'],detective:['mystery','detective'],'young adult':['young adult','juvenile fiction'],forest:['forests'],winter:['winter'],vampires:['vampires'],witches:['witches'],'science fiction':['science fiction','sci-fi','vědeckofantastické romány','vědeckofantastické povídky'],'historical fiction':['historical fiction'],'fairy tales':['fairy tales'],'falešný vztah':['fake dating','fake relationship'],'od rivality k lásce':['enemies to lovers','rivals to lovers'],'sci-fi':['science fiction','sci-fi','vědeckofantastické romány','vědeckofantastické povídky'],historie:['historical fiction'],les:['forests'],zima:['winter'],hvězdy:['stars'],škola:['schools','high school','college'],sport:['sports'],dětské:['juvenile fiction'],'new adult':['new adult'],čarodějnice:['witches'],upíři:['vampires'],vlkodlaci:['werewolves'],dystopie:['dystopia','dystopian'],horor:['horror'],pohádky:['fairy tales'],thriller:['thriller']};
    function subject(term){var values=subjects[term]||[term];return '('+values.map(function(t){return 'subject:'+quote(t);}).join(term==='romantasy'?' AND ':' OR ')+')';}
    function matches(b,terms){return Core.matchesTags?Core.matchesTags(b,terms):terms.every(function(t){return (b.tags||[]).some(function(s){return Core.norm(s)===Core.norm(t);});});}
    function tags(terms,filters){var list=(terms||[]).filter(function(t){return typeof t==='string';}).slice(0,5),f=filters||{};if(!list.length)return featured('for-you',f);var query=list.map(subject).join(' AND ');var jobs=[{source:'Open Library',run:function(){return olBrowse(query,f);}}];if(config.googleBooksApiKey)jobs.push({source:'Google Books',run:function(){return google(list.map(function(t){return 'subject:'+quote((subjects[t]||[t])[0]);}).join(' '),Object.assign({sort:'newest'},f));}});return aggregate(jobs,seeds.filter(function(b){return matches(b,list);}),f,function(b){return !bundles(b)&&matches(b,list);});}
    function featured(mode,filters){var f=filters||{};if(f.force)clearCache();var terms=mode==='ya'?['young adult']:mode==='romantasy'?['romantasy']:[],now=new Date().getFullYear(),topic=terms.length?terms.map(subject).join(' AND '):'(subject:"fantasy" OR subject:"romance" OR subject:"young adult")';var query=topic+' AND first_publish_year:['+(now-10)+' TO '+now+']';var jobs=[{source:'Open Library',run:function(){return olSearch(query,f,'new');}},{source:'Apple Books',run:function(){return apple(mode==='ya'?'young adult':mode==='romantasy'?'romantasy':'fantasy romance',f);}}];if(config.googleBooksApiKey)jobs.push({source:'Google Books',run:function(){return google(mode==='ya'?'subject:"young adult"':mode==='romantasy'?'subject:fantasy subject:romance':'subject:fiction',Object.assign({sort:'newest'},f));}});return aggregate(jobs,seeds.filter(function(b){return !terms.length||matches(b,terms);}),f,function(b){return !bundles(b)&&(!terms.length||matches(b,terms));});}
    function editionMetadata(original,d){var key=d.key||original.olEditionId||'',lang=language(d.languages||d.language),count=Core.integer(d.number_of_pages),published=date(d.publish_date),number=isbn((d.isbn_13||[]).concat(d.isbn_10||[]));var out=Object.assign({},original);if(/^\/books\/OL\d+M$/.test(key)){out.olEditionId=key;out.editionId=key;}if(number&&!out.isbn)out.isbn=number;if(lang&&(!out.language||!out.verified))out.language=lang;if(published&&(!out.year||!out.verified)){out.year=published;out.yearKind='edition';}if(count&&(!out.pages||!out.verified)){out.pages=count;out.pageSource='Open Library · ISBN / konkrétní vydání';}if(d.works&&d.works[0]&&/^\/works\/OL\d+W$/.test(d.works[0].key)){out.olWorkId=d.works[0].key;if(!out.workId)out.workId=out.olWorkId;}if(d.description)out.desc=text(d.description);if(!out.desc&&d.notes)out.desc=text(d.notes);if(Array.isArray(d.subjects))out.tags=(out.tags||[]).concat(d.subjects);if(d.covers&&d.covers[0]>0&&!(out.verified&&out.coverUrl)){out.coverUrl='https://covers.openlibrary.org/b/id/'+d.covers[0]+'-M.jpg';out.coverUrlL='https://covers.openlibrary.org/b/id/'+d.covers[0]+'-L.jpg';}if(d.series&&d.series.length&&!out.series)out.series=text(d.series[0]).slice(0,200);return clean(out);}
    function metadataKey(b){return b.isbn?'ISBN:'+b.isbn:/^\/books\/OL\d+M$/.test(b.olEditionId||b.id)?'OLID:'+(b.olEditionId||b.id).split('/').pop():'';}
    function enrichBatch(books,limit,resolveWork){var targets=books.filter(function(b){return (!b.pages||!b.language||!b.year||(resolveWork&&!b.olWorkId))&&metadataKey(b);}).slice(0,limit||18),keys=Array.from(new Set(targets.map(metadataKey)));if(!keys.length)return Promise.resolve(books);return request('https://openlibrary.org/api/books?bibkeys='+encodeURIComponent(keys.join(','))+'&format=json&jscmd=details','Open Library',24*HOUR).then(function(j){return books.map(function(b){var row=j[metadataKey(b)];return row&&row.details?editionMetadata(b,row.details):b;});}).catch(function(){return books;});}
    function ratings(book){var url=config.goodreadsRatingsUrl;if(!url)return Promise.resolve(book);var origin=o.origin||(root&&root.location&&root.location.origin)||'';try{var resolved=new URL(url,origin);if(!origin||resolved.origin!==origin||!/^https?:$/.test(resolved.protocol))return Promise.resolve(book);url=resolved.href;}catch(e){return Promise.resolve(book);}return request(url,'Goodreads',6*HOUR).then(function(feed){var rows=Array.isArray(feed)?feed:(feed.ratings||[]);if(!Array.isArray(rows))return book;var row=rows.find(function(r){return r&&r.isbn&&r.isbn===book.isbn;})||rows.find(function(r){return r&&r.workId&&r.workId===book.workId&&(!r.scope||r.scope==='work');});if(!row||!Core.validRating(row.rating)||!/^https:\/\/(?:www\.)?goodreads\.com\/book\/show\//.test(row.url||'')||!row.checkedAt)return book;return clean(Object.assign({},book,{grRating:row.rating,grCount:Core.integer(row.count,100000000),grUrl:row.url,grCheckedAt:row.checkedAt,grScope:row.scope==='work'?'work':'edition',grSnapshot:row.snapshot===true}));}).catch(function(){return book;});}
    function detail(book){
      var original=Object.assign({},book),choices=flat([book]).concat(seeds.filter(function(s){return workMatch(s,book);}));
      return enrichBatch(merge(linked(choices)),60,true).then(function(enriched){var out=enriched.find(function(b){return b.id===original.id;})||original;choices=enriched;var work=out.olWorkId||(/^\/works\/OL\d+W$/.test(out.id)?out.id:'');
        function loadWork(key){var tasks=[request('https://openlibrary.org'+key+'.json','Open Library',24*HOUR).then(function(d){if(d.description&&!out.desc)out.desc=text(d.description);if(Array.isArray(d.subjects))out.tags=(out.tags||[]).concat(d.subjects);}).catch(function(){}),request('https://openlibrary.org'+key+'/editions.json?limit=100&offset=0','Open Library',24*HOUR).then(function(j){if(!Array.isArray(j.entries))return;addEditions(j.entries,key);if(j.size>100)return request('https://openlibrary.org'+key+'/editions.json?limit=100&offset=100','Open Library',24*HOUR).then(function(next){if(Array.isArray(next.entries))addEditions(next.entries,key);}).catch(function(){});}).catch(function(){})];return Promise.all(tasks);}
        function addEditions(entries,key){entries.forEach(function(e){if(!/^\/books\/OL\d+M$/.test(e.key||'')||!e.title)return;var edition=Object.assign({},out,{id:e.key,editionId:e.key,olEditionId:e.key,olWorkId:key,title:e.title,source:'Open Library',verified:false,metadataSource:'',metadataSources:[],language:'',pages:0,year:null,isbn:'',pageSource:'',coverUrl:'',coverUrlL:'',spineUrl:'',link:'https://openlibrary.org'+e.key});['aRating','aCount','gRating','gCount','grRating','grCount','grUrl','grCheckedAt','grScope','grSnapshot','verifiedAt'].forEach(function(k){delete edition[k];});edition=editionMetadata(edition,e);if(!edition.language||!langCodes[edition.language])return;choices.push(edition);});}
        function lookup(){
          var titles=Array.from(new Set([out.title].concat(out.aliases||[]))).slice(0,5);
          function byTitle(){return olSearch('('+titles.map(function(t){return 'title:'+quote(t);}).join(' OR ')+') AND author:'+quote(out.author),{});}
          return (out.isbn?olSearch('isbn:'+out.isbn,{}).then(function(list){return list.length?list:byTitle();}):byTitle()).then(function(list){return linked(list).filter(function(b){return workMatch(b,out);});}).catch(function(){return [];});
        }
        var needsLookup=!work||!choices.some(function(b){return workMatch(b,out)&&Core.validRating(b.olRating);});
        var task=(needsLookup?lookup():Promise.resolve([])).then(function(found){choices=choices.concat(found);var foundWork=found.find(function(b){return b.olWorkId;});if(!work&&foundWork){work=foundWork.olWorkId;out.olWorkId=work;}return work?loadWork(work):null;});
        return task.then(function(){var all=merge(linked(choices));var selected=all.find(function(b){return Core.sameBook(b,out);})||out;out=Object.assign({},selected,out);if(!out.pages&&selected.pages){out.pages=selected.pages;out.pageSource=selected.pageSource;}if(!out.language&&selected.language)out.language=selected.language;if(!out.year&&selected.year)out.year=selected.year;if(!out.coverUrl&&selected.coverUrl)out.coverUrl=selected.coverUrl;if(!out.coverUrlL&&selected.coverUrlL)out.coverUrlL=selected.coverUrlL;if(!out.spineUrl&&selected.spineUrl)out.spineUrl=selected.spineUrl;
          // Open Library ratings belong to the work. Edition pages and Apple /
          // Google edition ratings remain attached to their own ISBN/version.
          var workRatings=all.concat([out]).filter(function(b){return workMatch(b,out)&&Core.validRating(b.olRating);}).sort(function(a,b){return Core.integer(b.olCount,100000000)-Core.integer(a.olCount,100000000);});
          if(workRatings.length){out.olRating=workRatings[0].olRating;out.olCount=workRatings[0].olCount;all=all.map(function(b){return workMatch(b,out)?Object.assign({},b,{olRating:out.olRating,olCount:out.olCount}):b;});}
          out=clean(out);return ratings(out).then(function(rated){rated.editions=all.filter(function(b){return workMatch(b,rated);});return rated;});});
      });
    }
    function clearCache(){cache.clear();if(storage)try{Object.keys(storage).filter(function(k){return k.indexOf('za_catalogue_v1:')===0;}).forEach(function(k){storage.removeItem(k);});}catch(e){}}
    return {search:search,tags:tags,featured:featured,detail:detail,clearCache:clearCache,_test:{mapOL:mapOL,mapApple:mapApple,mapGoogle:mapGoogle,editionMetadata:editionMetadata,language:language,enrichBatch:enrichBatch,request:request}};
  }
  var client=root?create():{};client.create=create;return client;
});
